/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apps;

import java.awt.BorderLayout;
import java.lang.Math;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Currency;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class program extends javax.swing.JFrame {
    
    static int hitungTotal(int total, int total_harga){
        int Jumlah_Harga = total + total_harga;
        return Jumlah_Harga;
    }
    static int Jumlah_Cashback(int total_harga, int Transaksi_uang ){
        return Transaksi_uang - total_harga;
    }
    static String moneyFormat(int nomer){
        Locale indo = new Locale("in", "ID");
        Currency rupiah = Currency.getInstance(indo);
        NumberFormat rupiahFormat = NumberFormat.getCurrencyInstance(indo);
        return rupiahFormat.format(nomer);
}

    /**
     * Creates new form program
     */
    public program() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        PilihBarang = new javax.swing.JComboBox<>();
        HargaBarang = new javax.swing.JTextField();
        JumlahBarang = new javax.swing.JTextField();
        TotalHarga = new javax.swing.JTextField();
        Transaksi = new javax.swing.JTextField();
        Cashback = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Data = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        struct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Kasir");
        setMinimumSize(null);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        base.setBackground(new java.awt.Color(4, 35, 119));
        base.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                baseComponentShown(evt);
            }
        });

        PilihBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolpoint", "Pensil 2B", "Penggaris", "Penghapus", "Sampul Buku", "Busur", "Glue Stick", "Rautan Pensil", " ", " " }));
        PilihBarang.setMaximumSize(null);
        PilihBarang.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PilihBarangComponentShown(evt);
            }
        });
        PilihBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihBarangActionPerformed(evt);
            }
        });

        HargaBarang.setEditable(false);
        HargaBarang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        HargaBarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HargaBarang.setMaximumSize(null);
        HargaBarang.setPreferredSize(new java.awt.Dimension(57, 20));
        HargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaBarangActionPerformed(evt);
            }
        });

        JumlahBarang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JumlahBarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JumlahBarang.setMaximumSize(null);
        JumlahBarang.setPreferredSize(new java.awt.Dimension(57, 20));
        JumlahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahBarangActionPerformed(evt);
            }
        });
        JumlahBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JumlahBarangKeyTyped(evt);
            }
        });

        TotalHarga.setEditable(false);
        TotalHarga.setFont(new java.awt.Font("Miriam Libre", 0, 36)); // NOI18N
        TotalHarga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalHarga.setText("0");
        TotalHarga.setToolTipText("");
        TotalHarga.setMaximumSize(null);

        Transaksi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Transaksi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Transaksi.setText("0");
        Transaksi.setMaximumSize(null);
        Transaksi.setPreferredSize(new java.awt.Dimension(57, 20));
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });
        Transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tekan(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TransaksiKeyTyped(evt);
            }
        });

        Cashback.setEditable(false);
        Cashback.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Cashback.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cashback.setText("0");
        Cashback.setMaximumSize(null);
        Cashback.setPreferredSize(new java.awt.Dimension(57, 20));
        Cashback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashbackActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(8, 66, 14));
        AddButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(160, 8, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setMinimumSize(null);

        Tabel_Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabel_Data);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nama Barang");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Harga");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Harga");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jumlah Barang");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Transaksi");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Kembalian");

        struct.setBackground(new java.awt.Color(238, 71, 23));
        struct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        struct.setText("Receipt");
        struct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                structActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JumlahBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PilihBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(TotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cashback, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(struct, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(TotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cashback, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PilihBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(42, 42, 42)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(struct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JumlahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahBarangActionPerformed

    private void HargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaBarangActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransaksiActionPerformed

    private void CashbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashbackActionPerformed

    private void PilihBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihBarangActionPerformed
        // TODO add your handling code here:
        switch(PilihBarang.getSelectedIndex()){
            case 0:
                HargaBarang.setText("2000");
                break;
            case 1:
                HargaBarang.setText("3000");
                break;
            case 2:
                HargaBarang.setText("1000");
                break;
            case 3:
                HargaBarang.setText("1500");
                break;
            case 4:
                HargaBarang.setText("2500");
                break;
            case 5:
                HargaBarang.setText("4000");
                break;
            case 6:
                HargaBarang.setText("7000");
                break;
            case 7:
                HargaBarang.setText("1000");
                break;
        }
    }//GEN-LAST:event_PilihBarangActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        try{
                //        mengambil data
            String Barang = (String) PilihBarang.getSelectedItem();
            int harga = Integer.parseInt(HargaBarang.getText());
            int jumlah = Integer.parseInt(JumlahBarang.getText());
            int total_harga = Integer.parseInt(TotalHarga.getText());
            int Transaksi_uang = Integer.parseInt(Transaksi.getText());
            //total harga
            int total = harga * jumlah;
            int Hitung_Total =hitungTotal(total,total_harga);
            TotalHarga.setText(String.valueOf(Hitung_Total));
            //format Rupiah
            String hrg_brg = moneyFormat(harga);
            String ttl_hrg = moneyFormat(total);
            //input data ke tabel
            tbl.addRow(new Object[]{
                Barang, jumlah, hrg_brg, ttl_hrg
            });
            Tabel_Data.setModel(tbl);
            JumlahBarang.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Data Kosong");
        }
        
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void baseComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_baseComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_baseComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Tabel_Data.setModel(tbl);
    }//GEN-LAST:event_formComponentShown

    private void PilihBarangComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PilihBarangComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_PilihBarangComponentShown

    private void tekan(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tekan
        // TODO add your handling code here:
        try{
            int total_harga = Integer.parseInt(TotalHarga.getText());
            int Transaksi_uang = Integer.parseInt(Transaksi.getText());
            int csbk = Jumlah_Cashback(total_harga, Transaksi_uang);
            String cash =moneyFormat(csbk);
//            Cashback.setText(String.valueOf(csbk));  
            Cashback.setText(cash);
        }catch(NumberFormatException e){
            
        }
    }//GEN-LAST:event_tekan

    private void JumlahBarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahBarangKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!Character.isDigit(karakter)){
            evt.consume();
        }
    }//GEN-LAST:event_JumlahBarangKeyTyped

    private void TransaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TransaksiKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!Character.isDigit(karakter)){
            evt.consume();
        }
    }//GEN-LAST:event_TransaksiKeyTyped

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini..?");
        switch(pilih){
            case JOptionPane.YES_OPTION:
                HargaBarang.setText(" ");
                JumlahBarang.setText(" ");
                TotalHarga.setText("0");
                Transaksi.setText("0");
                Cashback.setText("0");
                DefaultTableModel model = (DefaultTableModel) Tabel_Data.getModel();
                model.setRowCount(0);
                break;
        }
    }//GEN-LAST:event_clearActionPerformed

    private void structActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_structActionPerformed
        // TODO add your handling code here:
//        setLocationRelativeToonull);
//        deklarasi
        int ttl = Integer.parseInt(TotalHarga.getText());
        int trs = Integer.parseInt(Transaksi.getText());
        String kembalian = Cashback.getText();
        String transaksi = moneyFormat(trs);
        String total = moneyFormat(ttl);
//        tampilan
        JFrame frame = new JFrame("Struk Pembayaran");
        JTextArea text = new JTextArea();
        text.setEditable(false);
        text.setText(text.getText()+"\t                     Toko Jontor ATK \n");
        text.setText(text.getText()+"\t                Jalan Pemalang no 19 \n");
        text.setText(text.getText()+"\t                Telp. (0353) 426991\n");
        text.setText(text.getText()+"\n");
        text.setText(text.getText()+"---------------------------------------------------------------------------------------------------------------\n");
        text.setText(text.getText()+"No"+"\t Nama"+"\t Jumlah"+"\t   Harga"+"\t    Total"+" \n");
        for(int i = 0; i < Tabel_Data.getRowCount();i++){
            int a = i + 1;
            String Nama = Tabel_Data.getValueAt(i, 0).toString();
            String Jumlah = Tabel_Data.getValueAt(i, 1).toString();
            String Harga = Tabel_Data.getValueAt(i, 2).toString();
            String Total= Tabel_Data.getValueAt(i, 3).toString();
            text.setText(text.getText()+a+" \t"+Nama+"\t"+"    "+Jumlah+"\t"+Harga+"\t"+Total+"\n");
            text.setText(text.getText()+"\n");
        }
        text.setText(text.getText()+"---------------------------------------------------------------------------------------------------------------\n");
        text.setText(text.getText()+"\n");
        text.setText(text.getText()+"Total Harga \t\t= "+total+"\n");
        text.setText(text.getText()+"Jumlah Transaksi \t= "+transaksi+"\n");
        text.setText(text.getText()+"Kembalian \t\t= "+kembalian+"\n");
        JScrollPane jp = new JScrollPane(text);
        frame.getContentPane().add(jp);
        frame.setSize(462,450);
        frame.setVisible(true);
        
    }//GEN-LAST:event_structActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new program().setVisible(true);
        });
    }
    int Baris = 0;
    static Object Kolom[] = {"Nama Barang", "Jumlah Barang", "Harga Barang", "Jumlah Harga Barang"};
    DefaultTableModel tbl = new DefaultTableModel(Kolom,Baris);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField Cashback;
    private javax.swing.JTextField HargaBarang;
    private javax.swing.JTextField JumlahBarang;
    private javax.swing.JComboBox<String> PilihBarang;
    private javax.swing.JTable Tabel_Data;
    private javax.swing.JTextField TotalHarga;
    private javax.swing.JTextField Transaksi;
    private javax.swing.JPanel base;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton struct;
    // End of variables declaration//GEN-END:variables

    private void JOptionPane(Object object, String data_Kosong) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
